//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artech.WcfServices.Client.ServiceReferences {
    
    
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.artech.com/", ConfigurationName="ServiceReferences.IFileReader")]
public interface IFileReader {
        
    [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/IFileReader/Read", ReplyAction="http://www.artech.com/IFileReader/ReadResponse")]
    string Read(string fileName);
}
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileReaderChannel : Artech.WcfServices.Client.ServiceReferences.IFileReader, System.ServiceModel.IClientChannel {
    }
    
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FileReaderClient : System.ServiceModel.ClientBase<Artech.WcfServices.Client.ServiceReferences.IFileReader>, Artech.WcfServices.Client.ServiceReferences.IFileReader {
        
    public FileReaderClient() {
    }
        
    public FileReaderClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
        
    public FileReaderClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
        
    public FileReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
        
    public FileReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
        
    public string Read(string fileName) {
        return base.Channel.Read(fileName);
    }
}
}
